name: Slack Pull Request Open Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack pr open
      env: 
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        uses: rtCamp/action-slack-notify@v2
        SLACK_CHANNEL: '#mobile-automation'
